from enum import Enum


# DB constants
POSTGRES_DB = "POSTGRES_DB"
POSTGRES_USER = "POSTGRES_USER"
POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
POSTGRES_HOST = "POSTGRES_HOST"
POSTGRES_PORT = "POSTGRES_PORT"
POSTGRES_HOST_DEFAULT = "postgres"
POSTGRES_PORT_DEFAULT = 5432

class Tags(Enum):
  HEALTH_CHECK = "Health check"
  BOOKS = "Books"
